### ISSUE TITLE
H1: prevent frame encapsulation

### ISSUE THREAD

**Issue by kborer** [MetLifeLegalPlans/portunus#103]
Add headers to prevent cross frame scripting.

Add:
x-frame-options DENY

### References:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

### Report:

![Screenshot from 2020-07-17 18-30-58](https://user-images.githubusercontent.com/640862/87835642-b4419f00-c85b-11ea-81a1-b558c4b1b8be.png)

### Recommendation:

Please ensure all pages that gather user information prior to and during authentication are not vulnerable. The pages must prevent being encapsulated within a frameset of an unauthorized site. Listed below are different methods to prevent frames from becoming encapsulated. Depending upon your application's environment, one or more of the following solutions will need to be implemented.

Additionally, ensure that the X-FRAME-Options response header is applied to all pages. This header can be used with the most
appropriate attribute for your application:
• DENY

CSP 2.0 headers:
Addional defense in depth appoach: This can be added on top of the frame busting codes. However, this may not be honoured by old browsers.
CSP 2.0 has a new directive frame-ancestors.
To prevent all framing of your content use:
Content-Security-Policy: frame-ancestors 'none'

**Comment by kborer** [comment]
closed by #96

**Comment by ambikads** [comment]
Backend is taken care of. We will need to set X Frame Option to DENY for the frontend responses too. @markrawls

**Comment by markrawls** [comment]
Closed in [04472e182fcef2e72a9834fbbd94067e3b1d91f9](https://github.com/MetLifeLegalPlans/api-proxy/commit/04472e182fcef2e72a9834fbbd94067e3b1d91f9), new image pushed to ECR
