### ISSUE TITLE
H3: disable debug reporting in test environment

### ISSUE THREAD

**Issue by kborer** [MetLifeLegalPlans/portunus#105]
Tester notes that lots of debug information is printed that could help attackers:

### report
![Screenshot from 2020-07-17 18-43-53](https://user-images.githubusercontent.com/640862/87836347-bf95ca00-c85d-11ea-9b01-c3b66ccfdc25.png)

![Screenshot from 2020-07-17 18-44-21](https://user-images.githubusercontent.com/640862/87836346-bf95ca00-c85d-11ea-9d2a-8e3f8342510b.png)

![Screenshot from 2020-07-17 18-44-36](https://user-images.githubusercontent.com/640862/87836345-befd3380-c85d-11ea-8f03-f2d0655a5e4f.png)

![Screenshot from 2020-07-17 18-44-49](https://user-images.githubusercontent.com/640862/87836342-be649d00-c85d-11ea-8c20-aa8222e77599.png)

**Comment by ambikads** [comment]
Can we make it only for all test environments used externally like staging and primeon? Don't we not see it useful for other lower environments?

**Comment by kborer** [comment]
Yes
