### ISSUE TITLE
M6: enable emails in test environment

### ISSUE THREAD

**Issue by kborer** [MetLifeLegalPlans/portunus#111]
Tester could not very password reset functionality because they could not get emails. Enabling emails for Portunus should not be a problem.

### Report
![Screenshot from 2020-07-17 19-10-36](https://user-images.githubusercontent.com/640862/87837381-544df700-c861-11ea-9c6b-c17a0800cdac.png)

**Comment by ambikads** [comment]
This is done and tested. I got a password reset email and the reset worked.
