### ISSUE TITLE
L1: hide webserver version

### ISSUE THREAD

**Issue by kborer** [MetLifeLegalPlans/portunus#112]
### Report

![Screenshot from 2020-07-17 19-12-34](https://user-images.githubusercontent.com/640862/87837455-8c553a00-c861-11ea-945b-008b848b9ab2.png)

**Comment by ambikads** [comment]
Turning the DEBUG mode to false and authenticating the API calls makes this information not show on the browser.

**Comment by kborer** [comment]
This was the final Primeon security flaw. Nice work everyone

**Comment by ambikads** [comment]
This came back as still open. Can be taken care of after launch

**Comment by ambikads** [comment]
We don't show the server version anymore now that we are using Caddy.
