### ISSUE TITLE
LOGIN SETTINGS: Take the user to members services page when logo is clicked

### ISSUE THREAD

**Issue by ambikads** [MetLifeLegalPlans/portunus#166]
Clicking the logo in Login settings page from Members App should take the user to Services page.

https://www.notion.so/Update-logo-link-to-return-to-Category-Page-from-Login-settings-page-b18bbf65bfcf4504a191da1c66ffdb54

**Comment by hpetrow** [comment]
Note: should take to the services page if they are a member or eligible member and to account status page for non-members.

**Comment by hpetrow** [comment]
closed by https://github.com/MetLifeLegalPlans/members/pull/676

**Comment by hpetrow** [comment]
whoops, guess this isn't working.
