### ISSUE TITLE
Add email search API that returns portunus uids

### ISSUE THREAD

**Issue by cviveiro** [MetLifeLegalPlans/portunus#182]
This is something that we couldn't do with Members but would like to be able to in the future. We need the puids to link the Portunus user (which includes email) with the Members user (which doesn't include email). We'll need to be thoughtful about the search, normalize parts of it or make it take characters like `.` or caps well. We'll want to pass in the search string and return the puids of the matching users.

I think @hpetrow has specific ideas on how the search should work, if she wants to add them here.

**Comment by ambikads** [comment]
this is not deployed yet, re-opening
