### ISSUE TITLE
Disable Google and Facebook Auth for Members

### ISSUE THREAD

**Issue by hpetrow** [MetLifeLegalPlans/portunus#81]

**Comment by Ian-MacLeod** [comment]
Just to double check - this will mean taking off the social login for everyone because there is no way to distinguish between unauthenticated users on the login/register pages.

**Comment by hpetrow** [comment]
I see, including willing app users? I probably have no idea what I'm talking about, but the redirect url isn't available anywhere at that point?

**Comment by Ian-MacLeod** [comment]
Hmm, so we could show/hide the social auth based on the redirect url. It would technically still be possible to log in using Facebook/Google and use the Members app, but you would have to start from the willing app or manipulate the query parameter. Is that what we want?
