### ISSUE TITLE
ADMIN: Add user-specific login settings page for admin access

### ISSUE THREAD

**Issue by swang192** [MetLifeLegalPlans/portunus#82]
Based on the design, an admin should be able to edit a specific user's login credentials.
Looks like we'll need a separate view that handles getting login info by uuid, only accessible by admins.

![image](https://user-images.githubusercontent.com/14917593/86386111-5445d880-bc5f-11ea-993b-169e93cf0ae1.png)

**Comment by hpetrow** [comment]
requirements changed
