### ISSUE TITLE
Aetna SSO

### ISSUE THREAD

**Issue by kborer** [MetLifeLegalPlans/portunus#92]
Apparently, 7 years ago we decided to implement SSO for one sponsor. We'll have to add similar support to Portunus at some point.

<img width="583" alt="aetna_sso" src="https://user-images.githubusercontent.com/640862/87329751-7106c980-c505-11ea-8db0-9d379bb229f5.png">

PHP implementation:
https://github.com/MetLifeLegalPlans/members.legalplans.com/blob/members/SSO/index.php

**Comment by cviveiro** [comment]
Needed by launch?

**Comment by kborer** [comment]
tbd

**Comment by kborer** [comment]
haven't heard any complaints about this, so we'll drop it for now
